// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as store$0 from "../store/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../../../time/models.js";

/**
 * Action 一次同步的结果动作。
 * @readonly
 * @enum {string}
 */
export const Action = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    /**
     * 两侧一致，什么都没做
     */
    ActionNoop: "noop",

    /**
     * 本地配置已上传
     */
    ActionPushed: "pushed",

    /**
     * 远端配置已应用到本地
     */
    ActionPulled: "pulled",

    /**
     * 两侧都改过，等用户裁决
     */
    ActionConflict: "conflict",
};

/**
 * ConflictInfo 冲突时远端一侧的来源信息，供弹窗向用户交代「远端是谁写的」。
 */
export class ConflictInfo {
    /**
     * Creates a new ConflictInfo instance.
     * @param {Partial<ConflictInfo>} [$$source = {}] - The source object to create the ConflictInfo.
     */
    constructor($$source = {}) {
        if (!("remoteDeviceName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["remoteDeviceName"] = "";
        }
        if (!("remoteUpdatedAt" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["remoteUpdatedAt"] = null;
        }
        if (!("remoteRevision" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["remoteRevision"] = 0;
        }
        if (!("detectedAt" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["detectedAt"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ConflictInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ConflictInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ConflictInfo(/** @type {Partial<ConflictInfo>} */($$parsedSource));
    }
}

/**
 * Result 一次同步的结果。
 */
export class Result {
    /**
     * Creates a new Result instance.
     * @param {Partial<Result>} [$$source = {}] - The source object to create the Result.
     */
    constructor($$source = {}) {
        if (!("action" in $$source)) {
            /**
             * @member
             * @type {Action}
             */
            this["action"] = Action.$zero;
        }
        if (!("conflict" in $$source)) {
            /**
             * Conflict 仅 ActionConflict 时非空。
             * @member
             * @type {ConflictInfo | null}
             */
            this["conflict"] = null;
        }
        if (!("settings" in $$source)) {
            /**
             * Settings 仅 ActionPulled 时非空：把应用后的完整设置一并回给前端，
             * 省去「同步完再查一次设置」的往返，也避免两次调用之间的状态错位。
             * @member
             * @type {store$0.Settings | null}
             */
            this["settings"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Result instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Result}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType1;
        const $$createField2_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("conflict" in $$parsedSource) {
            $$parsedSource["conflict"] = $$createField1_0($$parsedSource["conflict"]);
        }
        if ("settings" in $$parsedSource) {
            $$parsedSource["settings"] = $$createField2_0($$parsedSource["settings"]);
        }
        return new Result(/** @type {Partial<Result>} */($$parsedSource));
    }
}

/**
 * Status 对外暴露的同步状态（供设置页展示）。
 */
export class Status {
    /**
     * Creates a new Status instance.
     * @param {Partial<Status>} [$$source = {}] - The source object to create the Status.
     */
    constructor($$source = {}) {
        if (!("lastSyncAt" in $$source)) {
            /**
             * LastSyncAt 上次同步成功时间；从未成功时为 null。
             * 用指针而非零值时间：让前端不必判别 "0001-01-01" 这种魔法值。
             * @member
             * @type {time$0.Time | null}
             */
            this["lastSyncAt"] = null;
        }
        if (!("lastError" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["lastError"] = "";
        }
        if (!("hasPending" in $$source)) {
            /**
             * 本地有改动尚未推送
             * @member
             * @type {boolean}
             */
            this["hasPending"] = false;
        }
        if (!("conflict" in $$source)) {
            /**
             * @member
             * @type {ConflictInfo | null}
             */
            this["conflict"] = null;
        }
        if (!("deviceName" in $$source)) {
            /**
             * 本机名，与远端一侧对照展示
             * @member
             * @type {string}
             */
            this["deviceName"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Status instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Status}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("conflict" in $$parsedSource) {
            $$parsedSource["conflict"] = $$createField3_0($$parsedSource["conflict"]);
        }
        return new Status(/** @type {Partial<Status>} */($$parsedSource));
    }
}

/**
 * WebDAVInput 前端提交的连接配置。
 * 
 * Password 为空表示**保持原密码不变** —— 前端拿不到现有密码，
 * 用户只改地址时不该被迫重新输入一遍。要清空密码得用 Clear。
 */
export class WebDAVInput {
    /**
     * Creates a new WebDAVInput instance.
     * @param {Partial<WebDAVInput>} [$$source = {}] - The source object to create the WebDAVInput.
     */
    constructor($$source = {}) {
        if (!("enabled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["enabled"] = false;
        }
        if (!("url" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["url"] = "";
        }
        if (!("username" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["username"] = "";
        }
        if (!("password" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["password"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WebDAVInput instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {WebDAVInput}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new WebDAVInput(/** @type {Partial<WebDAVInput>} */($$parsedSource));
    }
}

/**
 * WebDAVView 回给前端的连接配置。
 * 
 * ⚠️ 只有 HasPassword，没有任何密码字段。密码不出现在返回给前端的任何结构里：
 * 一进 IPC 就会落到 webview 的内存与可能的日志里。
 * TestViewHasNoPasswordField 用反射守住这条。
 */
export class WebDAVView {
    /**
     * Creates a new WebDAVView instance.
     * @param {Partial<WebDAVView>} [$$source = {}] - The source object to create the WebDAVView.
     */
    constructor($$source = {}) {
        if (!("enabled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["enabled"] = false;
        }
        if (!("url" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["url"] = "";
        }
        if (!("username" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["username"] = "";
        }
        if (!("hasPassword" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["hasPassword"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WebDAVView instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {WebDAVView}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new WebDAVView(/** @type {Partial<WebDAVView>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = ConflictInfo.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = store$0.Settings.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
