// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Installed 已安装的一个字体族。安装清单靠扫描目录得出，不落安装元数据：
 * 删目录即卸载，无状态、无迁移；代价是无法显示「有新版本可升级」，本次不做。
 */
export class Installed {
    /**
     * Creates a new Installed instance.
     * @param {Partial<Installed>} [$$source = {}] - The source object to create the Installed.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("files" in $$source)) {
            /**
             * @member
             * @type {InstalledFile[]}
             */
            this["files"] = [];
        }
        if (!("totalSize" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["totalSize"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Installed instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Installed}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("files" in $$parsedSource) {
            $$parsedSource["files"] = $$createField1_0($$parsedSource["files"]);
        }
        return new Installed(/** @type {Partial<Installed>} */($$parsedSource));
    }
}

/**
 * InstalledFile 已安装字体族里的单个文件。
 */
export class InstalledFile {
    /**
     * Creates a new InstalledFile instance.
     * @param {Partial<InstalledFile>} [$$source = {}] - The source object to create the InstalledFile.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("size" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["size"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new InstalledFile instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {InstalledFile}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new InstalledFile(/** @type {Partial<InstalledFile>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = InstalledFile.createFrom;
const $$createType1 = $Create.Array($$createType0);
