// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * CategoryService 分类管理相关的绑定方法。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as store$0 from "../internal/store/models.js";

/**
 * AddCategory 新增分类。parentID 为 0 表示根分类。
 * @param {string} name
 * @param {number} parentID
 * @returns {$CancellablePromise<store$0.Category | null>}
 */
export function AddCategory(name, parentID) {
    return $Call.ByID(2710973415, name, parentID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * DeleteCategory 删除分类（级联删除子分类，其下订阅源置为未分类）。
 * @param {number} id
 * @returns {$CancellablePromise<void>}
 */
export function DeleteCategory(id) {
    return $Call.ByID(2725099775, id);
}

/**
 * GetCategoryWithFeeds 获取分类及其下订阅源（含未读计数）。
 * @param {number} id
 * @returns {$CancellablePromise<store$0.CategoryWithFeeds | null>}
 */
export function GetCategoryWithFeeds(id) {
    return $Call.ByID(2251468721, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * GetUncategorizedFeeds 获取未分类的订阅源。
 * @returns {$CancellablePromise<store$0.FeedWithUnread[]>}
 */
export function GetUncategorizedFeeds() {
    return $Call.ByID(1753309219).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * ListCategories 列出全部分类。
 * @returns {$CancellablePromise<store$0.Category[]>}
 */
export function ListCategories() {
    return $Call.ByID(49027380).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType6($result);
    }));
}

/**
 * MoveToCategory 将订阅源移动到指定分类。categoryID 为 0 表示移出分类（未分类）。
 * @param {number} feedID
 * @param {number} categoryID
 * @returns {$CancellablePromise<void>}
 */
export function MoveToCategory(feedID, categoryID) {
    return $Call.ByID(2421320500, feedID, categoryID);
}

/**
 * UpdateCategory 更新分类（名称、父级、排序）。
 * @param {store$0.Category} category
 * @returns {$CancellablePromise<void>}
 */
export function UpdateCategory(category) {
    return $Call.ByID(1638670909, category);
}

// Private type creation functions
const $$createType0 = store$0.Category.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = store$0.CategoryWithFeeds.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = store$0.FeedWithUnread.createFrom;
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = $Create.Array($$createType0);
