// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * CloudBackupService 提供独立于配置同步的数据库云备份能力。
 * 
 * 云备份是不可变快照 + 手动恢复，不会把数据库文件加入配置同步引擎，也不会
 * 自动覆盖本机正在使用的数据库。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as cloudbackup$0 from "../internal/cloudbackup/models.js";

/**
 * @returns {$CancellablePromise<cloudbackup$0.BackupInfo>}
 */
export function BackupDatabaseToCloud() {
    return $Call.ByID(3744592372).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * CloudBackupRemotePath 返回备份远端目录，供设置页说明实际存储位置。
 * @returns {$CancellablePromise<string>}
 */
export function CloudBackupRemotePath() {
    return $Call.ByID(625500397);
}

/**
 * @returns {$CancellablePromise<cloudbackup$0.Config>}
 */
export function GetCloudBackupConfig() {
    return $Call.ByID(3500043692).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @returns {$CancellablePromise<cloudbackup$0.Status>}
 */
export function GetCloudBackupStatus() {
    return $Call.ByID(1124581804).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * @returns {$CancellablePromise<cloudbackup$0.BackupInfo[]>}
 */
export function ListCloudBackups() {
    return $Call.ByID(3825008301).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * @param {string} id
 * @returns {$CancellablePromise<cloudbackup$0.RestoreResult>}
 */
export function RestoreDatabaseFromCloud(id) {
    return $Call.ByID(184866085, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * @param {cloudbackup$0.Config} cfg
 * @returns {$CancellablePromise<void>}
 */
export function SaveCloudBackupConfig(cfg) {
    return $Call.ByID(1309639505, cfg);
}

// Private type creation functions
const $$createType0 = cloudbackup$0.BackupInfo.createFrom;
const $$createType1 = cloudbackup$0.Config.createFrom;
const $$createType2 = cloudbackup$0.Status.createFrom;
const $$createType3 = $Create.Array($$createType0);
const $$createType4 = cloudbackup$0.RestoreResult.createFrom;
