// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * FeedService 订阅源管理与刷新相关的绑定方法。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as store$0 from "../internal/store/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AddFeed 新增订阅源：抓取并解析以补全元信息，入库后立即拉取一次文章。
 * @param {string} feedURL
 * @returns {$CancellablePromise<store$0.Feed | null>}
 */
export function AddFeed(feedURL) {
    return $Call.ByID(3427241815, feedURL).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * DeleteFeed 删除订阅源（级联删除其文章）。
 * @param {number} id
 * @returns {$CancellablePromise<void>}
 */
export function DeleteFeed(id) {
    return $Call.ByID(2843475279, id);
}

/**
 * ForceRefreshAll 强制刷新全部订阅源（忽略条件 GET）。
 * @returns {$CancellablePromise<$models.RefreshOutcome[]>}
 */
export function ForceRefreshAll() {
    return $Call.ByID(2348969661).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * ForceRefreshFeed 强制刷新单个订阅源（忽略条件 GET）。
 * @param {number} id
 * @returns {$CancellablePromise<$models.RefreshOutcome>}
 */
export function ForceRefreshFeed(id) {
    return $Call.ByID(887799398, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * GetFeed 按 ID 获取订阅源。
 * @param {number} id
 * @returns {$CancellablePromise<store$0.Feed | null>}
 */
export function GetFeed(id) {
    return $Call.ByID(709555920, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * ListFeeds 列出全部订阅源。
 * @returns {$CancellablePromise<store$0.Feed[]>}
 */
export function ListFeeds() {
    return $Call.ByID(3917230141).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * ListFeedsWithUnread 列出全部订阅源及未读计数（用于侧栏）。
 * @returns {$CancellablePromise<store$0.FeedWithUnread[]>}
 */
export function ListFeedsWithUnread() {
    return $Call.ByID(2074177454).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType6($result);
    }));
}

/**
 * PauseFeed 暂停订阅源自动更新。
 * @param {number} id
 * @returns {$CancellablePromise<void>}
 */
export function PauseFeed(id) {
    return $Call.ByID(1344780130, id);
}

/**
 * RefreshAll 手动刷新全部订阅源（条件 GET）。
 * @returns {$CancellablePromise<$models.RefreshOutcome[]>}
 */
export function RefreshAll() {
    return $Call.ByID(2574435382).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * RefreshFeed 手动刷新单个订阅源（条件 GET）。
 * @param {number} id
 * @returns {$CancellablePromise<$models.RefreshOutcome>}
 */
export function RefreshFeed(id) {
    return $Call.ByID(18613039, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * ResumeFeed 恢复订阅源自动更新。
 * @param {number} id
 * @returns {$CancellablePromise<void>}
 */
export function ResumeFeed(id) {
    return $Call.ByID(3521358343, id);
}

/**
 * UpdateFeed 更新订阅源（标题、分类、间隔、上限等）。
 * @param {store$0.Feed} feed
 * @returns {$CancellablePromise<void>}
 */
export function UpdateFeed(feed) {
    return $Call.ByID(823973977, feed);
}

// Private type creation functions
const $$createType0 = store$0.Feed.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $models.RefreshOutcome.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = $Create.Array($$createType0);
const $$createType5 = store$0.FeedWithUnread.createFrom;
const $$createType6 = $Create.Array($$createType5);
