// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ItemService 文章查询与操作相关的绑定方法。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as store$0 from "../internal/store/models.js";

/**
 * AddNote 更新（新增/覆盖）文章笔记。
 * @param {number} id
 * @param {string} note
 * @returns {$CancellablePromise<void>}
 */
export function AddNote(id, note) {
    return $Call.ByID(1925996590, id, note);
}

/**
 * BatchMarkRead 批量标记文章为已读。
 * @param {number[]} ids
 * @returns {$CancellablePromise<void>}
 */
export function BatchMarkRead(ids) {
    return $Call.ByID(2901900944, ids);
}

/**
 * GetItem 按 ID 获取文章。
 * @param {number} id
 * @returns {$CancellablePromise<store$0.Item | null>}
 */
export function GetItem(id) {
    return $Call.ByID(3108011898, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * GetUnreadCount 获取全局未读总数。
 * @returns {$CancellablePromise<number>}
 */
export function GetUnreadCount() {
    return $Call.ByID(803109197);
}

/**
 * ListItems 列出文章：feedID > 0 时按源过滤，否则返回全部。
 * @param {number} feedID
 * @param {number} limit
 * @param {number} offset
 * @returns {$CancellablePromise<store$0.Item[]>}
 */
export function ListItems(feedID, limit, offset) {
    return $Call.ByID(1416322961, feedID, limit, offset).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * ListItemsLight 列出文章（轻量版本，不含 content）：feedID > 0 时按源过滤，否则返回全部。
 * @param {number} feedID
 * @param {number} limit
 * @param {number} offset
 * @returns {$CancellablePromise<store$0.ItemLight[]>}
 */
export function ListItemsLight(feedID, limit, offset) {
    return $Call.ByID(2640441307, feedID, limit, offset).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * ListStarredItems 列出星标文章。
 * @param {number} limit
 * @param {number} offset
 * @returns {$CancellablePromise<store$0.Item[]>}
 */
export function ListStarredItems(limit, offset) {
    return $Call.ByID(2077543422, limit, offset).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * ListStarredItemsLight 列出星标文章（轻量版本）。
 * @param {number} limit
 * @param {number} offset
 * @returns {$CancellablePromise<store$0.ItemLight[]>}
 */
export function ListStarredItemsLight(limit, offset) {
    return $Call.ByID(422992066, limit, offset).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * ListUnreadItems 列出未读文章。
 * @param {number} limit
 * @param {number} offset
 * @returns {$CancellablePromise<store$0.Item[]>}
 */
export function ListUnreadItems(limit, offset) {
    return $Call.ByID(1806062296, limit, offset).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * ListUnreadItemsLight 列出未读文章（轻量版本）。
 * @param {number} limit
 * @param {number} offset
 * @returns {$CancellablePromise<store$0.ItemLight[]>}
 */
export function ListUnreadItemsLight(limit, offset) {
    return $Call.ByID(935704524, limit, offset).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * MarkAllReadByFeed 标记某订阅源全部文章为已读。
 * @param {number} feedID
 * @returns {$CancellablePromise<void>}
 */
export function MarkAllReadByFeed(feedID) {
    return $Call.ByID(4083203108, feedID);
}

/**
 * MarkRead 标记文章为已读。
 * @param {number} id
 * @returns {$CancellablePromise<void>}
 */
export function MarkRead(id) {
    return $Call.ByID(3852800266, id);
}

/**
 * MarkUnread 标记文章为未读。
 * @param {number} id
 * @returns {$CancellablePromise<void>}
 */
export function MarkUnread(id) {
    return $Call.ByID(2510944193, id);
}

/**
 * SearchItems 全文搜索文章（标题/摘要/笔记）。
 * @param {string} keyword
 * @param {number} limit
 * @param {number} offset
 * @returns {$CancellablePromise<store$0.Item[]>}
 */
export function SearchItems(keyword, limit, offset) {
    return $Call.ByID(2754513273, keyword, limit, offset).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * ToggleStar 切换文章星标状态。
 * @param {number} id
 * @returns {$CancellablePromise<void>}
 */
export function ToggleStar(id) {
    return $Call.ByID(2140821479, id);
}

// Private type creation functions
const $$createType0 = store$0.Item.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Array($$createType0);
const $$createType3 = store$0.ItemLight.createFrom;
const $$createType4 = $Create.Array($$createType3);
