// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * FeedPreview 添加订阅前的检测预览信息（不入库）。
 */
export class FeedPreview {
    /**
     * Creates a new FeedPreview instance.
     * @param {Partial<FeedPreview>} [$$source = {}] - The source object to create the FeedPreview.
     */
    constructor($$source = {}) {
        if (!("url" in $$source)) {
            /**
             * 实际可订阅的 Feed URL（网页输入时为发现到的地址）
             * @member
             * @type {string}
             */
            this["url"] = "";
        }
        if (!("title" in $$source)) {
            /**
             * 解析到的源标题
             * @member
             * @type {string}
             */
            this["title"] = "";
        }
        if (!("description" in $$source)) {
            /**
             * 源描述
             * @member
             * @type {string}
             */
            this["description"] = "";
        }
        if (!("link" in $$source)) {
            /**
             * 站点主页链接
             * @member
             * @type {string}
             */
            this["link"] = "";
        }
        if (!("icon" in $$source)) {
            /**
             * favicon URL
             * @member
             * @type {string}
             */
            this["icon"] = "";
        }
        if (!("itemCount" in $$source)) {
            /**
             * 当前抓取到的文章数
             * @member
             * @type {number}
             */
            this["itemCount"] = 0;
        }
        if (!("alreadyAdded" in $$source)) {
            /**
             * 该源是否已订阅
             * @member
             * @type {boolean}
             */
            this["alreadyAdded"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FeedPreview instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {FeedPreview}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FeedPreview(/** @type {Partial<FeedPreview>} */($$parsedSource));
    }
}

/**
 * ImportResult 导入结果统计。
 */
export class ImportResult {
    /**
     * Creates a new ImportResult instance.
     * @param {Partial<ImportResult>} [$$source = {}] - The source object to create the ImportResult.
     */
    constructor($$source = {}) {
        if (!("categories" in $$source)) {
            /**
             * 新建分类数
             * @member
             * @type {number}
             */
            this["categories"] = 0;
        }
        if (!("feeds" in $$source)) {
            /**
             * 新增订阅源数
             * @member
             * @type {number}
             */
            this["feeds"] = 0;
        }
        if (!("skipped" in $$source)) {
            /**
             * 已存在而跳过的订阅源数
             * @member
             * @type {number}
             */
            this["skipped"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ImportResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ImportResult}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ImportResult(/** @type {Partial<ImportResult>} */($$parsedSource));
    }
}

/**
 * RefreshOutcome 单个订阅源刷新结果（对前端友好的可序列化形态）。
 */
export class RefreshOutcome {
    /**
     * Creates a new RefreshOutcome instance.
     * @param {Partial<RefreshOutcome>} [$$source = {}] - The source object to create the RefreshOutcome.
     */
    constructor($$source = {}) {
        if (!("feedId" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["feedId"] = 0;
        }
        if (!("newItems" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["newItems"] = 0;
        }
        if (!("notModified" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["notModified"] = false;
        }
        if (!("error" in $$source)) {
            /**
             * 该源抓取失败时的错误信息，空表示成功
             * @member
             * @type {string}
             */
            this["error"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RefreshOutcome instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {RefreshOutcome}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RefreshOutcome(/** @type {Partial<RefreshOutcome>} */($$parsedSource));
    }
}
