// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * ConnectionTestResult 「测试连接」的逐步结果。
 */
export class ConnectionTestResult {
    /**
     * Creates a new ConnectionTestResult instance.
     * @param {Partial<ConnectionTestResult>} [$$source = {}] - The source object to create the ConnectionTestResult.
     */
    constructor($$source = {}) {
        if (!("ok" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["ok"] = false;
        }
        if (!("step" in $$source)) {
            /**
             * Step 失败的步骤：connect / mkcol / write；成功时为空。
             * @member
             * @type {string}
             */
            this["step"] = "";
        }
        if (!("message" in $$source)) {
            /**
             * Message 失败原因（面向用户）。
             * @member
             * @type {string}
             */
            this["message"] = "";
        }
        if (!("hint" in $$source)) {
            /**
             * Hint 可操作的建议，可能为空。
             * @member
             * @type {string}
             */
            this["hint"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ConnectionTestResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ConnectionTestResult}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ConnectionTestResult(/** @type {Partial<ConnectionTestResult>} */($$parsedSource));
    }
}

/**
 * FeedPreview 添加订阅前的检测预览信息（不入库）。
 */
export class FeedPreview {
    /**
     * Creates a new FeedPreview instance.
     * @param {Partial<FeedPreview>} [$$source = {}] - The source object to create the FeedPreview.
     */
    constructor($$source = {}) {
        if (!("url" in $$source)) {
            /**
             * 实际可订阅的 Feed URL（网页输入时为发现到的地址）
             * @member
             * @type {string}
             */
            this["url"] = "";
        }
        if (!("title" in $$source)) {
            /**
             * 解析到的源标题
             * @member
             * @type {string}
             */
            this["title"] = "";
        }
        if (!("description" in $$source)) {
            /**
             * 源描述
             * @member
             * @type {string}
             */
            this["description"] = "";
        }
        if (!("link" in $$source)) {
            /**
             * 站点主页链接
             * @member
             * @type {string}
             */
            this["link"] = "";
        }
        if (!("icon" in $$source)) {
            /**
             * favicon URL
             * @member
             * @type {string}
             */
            this["icon"] = "";
        }
        if (!("itemCount" in $$source)) {
            /**
             * 当前抓取到的文章数
             * @member
             * @type {number}
             */
            this["itemCount"] = 0;
        }
        if (!("alreadyAdded" in $$source)) {
            /**
             * 该源是否已订阅
             * @member
             * @type {boolean}
             */
            this["alreadyAdded"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FeedPreview instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {FeedPreview}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FeedPreview(/** @type {Partial<FeedPreview>} */($$parsedSource));
    }
}

/**
 * ImportResult 导入结果统计。
 */
export class ImportResult {
    /**
     * Creates a new ImportResult instance.
     * @param {Partial<ImportResult>} [$$source = {}] - The source object to create the ImportResult.
     */
    constructor($$source = {}) {
        if (!("categories" in $$source)) {
            /**
             * 新建分类数
             * @member
             * @type {number}
             */
            this["categories"] = 0;
        }
        if (!("feeds" in $$source)) {
            /**
             * 新增订阅源数
             * @member
             * @type {number}
             */
            this["feeds"] = 0;
        }
        if (!("skipped" in $$source)) {
            /**
             * 已存在而跳过的订阅源数
             * @member
             * @type {number}
             */
            this["skipped"] = 0;
        }
        if (!("newFeeds" in $$source)) {
            /**
             * 新建的订阅源与分类详情，供前端增量追加（无需全量 reload）。
             * @member
             * @type {NewFeed[]}
             */
            this["newFeeds"] = [];
        }
        if (!("newCategories" in $$source)) {
            /**
             * @member
             * @type {NewCategory[]}
             */
            this["newCategories"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ImportResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ImportResult}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType1;
        const $$createField4_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("newFeeds" in $$parsedSource) {
            $$parsedSource["newFeeds"] = $$createField3_0($$parsedSource["newFeeds"]);
        }
        if ("newCategories" in $$parsedSource) {
            $$parsedSource["newCategories"] = $$createField4_0($$parsedSource["newCategories"]);
        }
        return new ImportResult(/** @type {Partial<ImportResult>} */($$parsedSource));
    }
}

/**
 * NewCategory 新建分类概要（供前端增量追加到 Store）。
 */
export class NewCategory {
    /**
     * Creates a new NewCategory instance.
     * @param {Partial<NewCategory>} [$$source = {}] - The source object to create the NewCategory.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["id"] = 0;
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("parentId" in $$source)) {
            /**
             * @member
             * @type {number | null}
             */
            this["parentId"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new NewCategory instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {NewCategory}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new NewCategory(/** @type {Partial<NewCategory>} */($$parsedSource));
    }
}

/**
 * NewFeed 新建订阅源概要（供前端增量追加到 Store）。
 */
export class NewFeed {
    /**
     * Creates a new NewFeed instance.
     * @param {Partial<NewFeed>} [$$source = {}] - The source object to create the NewFeed.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["id"] = 0;
        }
        if (!("url" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["url"] = "";
        }
        if (!("title" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["title"] = "";
        }
        if (!("link" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["link"] = "";
        }
        if (!("categoryId" in $$source)) {
            /**
             * @member
             * @type {number | null}
             */
            this["categoryId"] = null;
        }
        if (!("updateInterval" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["updateInterval"] = 0;
        }
        if (!("maxItems" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["maxItems"] = 0;
        }
        if (!("status" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["status"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new NewFeed instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {NewFeed}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new NewFeed(/** @type {Partial<NewFeed>} */($$parsedSource));
    }
}

/**
 * RefreshOutcome 单个订阅源刷新结果（对前端友好的可序列化形态）。
 */
export class RefreshOutcome {
    /**
     * Creates a new RefreshOutcome instance.
     * @param {Partial<RefreshOutcome>} [$$source = {}] - The source object to create the RefreshOutcome.
     */
    constructor($$source = {}) {
        if (!("feedId" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["feedId"] = 0;
        }
        if (!("newItems" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["newItems"] = 0;
        }
        if (!("notModified" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["notModified"] = false;
        }
        if (!("error" in $$source)) {
            /**
             * 该源抓取失败时的错误信息，空表示成功
             * @member
             * @type {string}
             */
            this["error"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RefreshOutcome instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {RefreshOutcome}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RefreshOutcome(/** @type {Partial<RefreshOutcome>} */($$parsedSource));
    }
}

/**
 * WebDAVInput 前端提交的 WebDAV 配置表单。密码传空串表示保持原密码不变。
 */
export class WebDAVInput {
    /**
     * Creates a new WebDAVInput instance.
     * @param {Partial<WebDAVInput>} [$$source = {}] - The source object to create the WebDAVInput.
     */
    constructor($$source = {}) {
        if (!("url" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["url"] = "";
        }
        if (!("username" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["username"] = "";
        }
        if (!("password" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["password"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WebDAVInput instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {WebDAVInput}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new WebDAVInput(/** @type {Partial<WebDAVInput>} */($$parsedSource));
    }
}

/**
 * WebDAVView 不含密码的 WebDAV 配置视图，供前端展示。
 */
export class WebDAVView {
    /**
     * Creates a new WebDAVView instance.
     * @param {Partial<WebDAVView>} [$$source = {}] - The source object to create the WebDAVView.
     */
    constructor($$source = {}) {
        if (!("url" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["url"] = "";
        }
        if (!("username" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["username"] = "";
        }
        if (!("hasPassword" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["hasPassword"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WebDAVView instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {WebDAVView}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new WebDAVView(/** @type {Partial<WebDAVView>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = NewFeed.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = NewCategory.createFrom;
const $$createType3 = $Create.Array($$createType2);
