// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * ConnectionTestResult 「测试连接」的逐步结果。
 * 
 * 有意用结构体而非 error 返回：Wails 把 error 压成一个字符串，前端无法用
 * errors.Is 判别，也就没法针对「认证失败」渲染服务商特定建议（如坚果云需用
 * 应用密码）。把「哪一步失败」与「建议」作为数据回去，前端才能照 errors.Is
 * 的判别结果那样分支。
 */
export class ConnectionTestResult {
    /**
     * Creates a new ConnectionTestResult instance.
     * @param {Partial<ConnectionTestResult>} [$$source = {}] - The source object to create the ConnectionTestResult.
     */
    constructor($$source = {}) {
        if (!("ok" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["ok"] = false;
        }
        if (!("step" in $$source)) {
            /**
             * Step 失败的步骤：connect / mkcol / write / delete；成功时为空。
             * @member
             * @type {string}
             */
            this["step"] = "";
        }
        if (!("message" in $$source)) {
            /**
             * Message 失败原因（面向用户）。
             * @member
             * @type {string}
             */
            this["message"] = "";
        }
        if (!("hint" in $$source)) {
            /**
             * Hint 可操作的建议，可能为空。与 Message 分开，便于前端用不同字号展示。
             * @member
             * @type {string}
             */
            this["hint"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ConnectionTestResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ConnectionTestResult}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ConnectionTestResult(/** @type {Partial<ConnectionTestResult>} */($$parsedSource));
    }
}

/**
 * FeedPreview 添加订阅前的检测预览信息（不入库）。
 */
export class FeedPreview {
    /**
     * Creates a new FeedPreview instance.
     * @param {Partial<FeedPreview>} [$$source = {}] - The source object to create the FeedPreview.
     */
    constructor($$source = {}) {
        if (!("url" in $$source)) {
            /**
             * 实际可订阅的 Feed URL（网页输入时为发现到的地址）
             * @member
             * @type {string}
             */
            this["url"] = "";
        }
        if (!("title" in $$source)) {
            /**
             * 解析到的源标题
             * @member
             * @type {string}
             */
            this["title"] = "";
        }
        if (!("description" in $$source)) {
            /**
             * 源描述
             * @member
             * @type {string}
             */
            this["description"] = "";
        }
        if (!("link" in $$source)) {
            /**
             * 站点主页链接
             * @member
             * @type {string}
             */
            this["link"] = "";
        }
        if (!("icon" in $$source)) {
            /**
             * favicon URL
             * @member
             * @type {string}
             */
            this["icon"] = "";
        }
        if (!("itemCount" in $$source)) {
            /**
             * 当前抓取到的文章数
             * @member
             * @type {number}
             */
            this["itemCount"] = 0;
        }
        if (!("alreadyAdded" in $$source)) {
            /**
             * 该源是否已订阅
             * @member
             * @type {boolean}
             */
            this["alreadyAdded"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FeedPreview instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {FeedPreview}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FeedPreview(/** @type {Partial<FeedPreview>} */($$parsedSource));
    }
}

/**
 * ImportResult 导入结果统计。
 */
export class ImportResult {
    /**
     * Creates a new ImportResult instance.
     * @param {Partial<ImportResult>} [$$source = {}] - The source object to create the ImportResult.
     */
    constructor($$source = {}) {
        if (!("categories" in $$source)) {
            /**
             * 新建分类数
             * @member
             * @type {number}
             */
            this["categories"] = 0;
        }
        if (!("feeds" in $$source)) {
            /**
             * 新增订阅源数
             * @member
             * @type {number}
             */
            this["feeds"] = 0;
        }
        if (!("skipped" in $$source)) {
            /**
             * 已存在而跳过的订阅源数
             * @member
             * @type {number}
             */
            this["skipped"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ImportResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ImportResult}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ImportResult(/** @type {Partial<ImportResult>} */($$parsedSource));
    }
}

/**
 * RefreshOutcome 单个订阅源刷新结果（对前端友好的可序列化形态）。
 */
export class RefreshOutcome {
    /**
     * Creates a new RefreshOutcome instance.
     * @param {Partial<RefreshOutcome>} [$$source = {}] - The source object to create the RefreshOutcome.
     */
    constructor($$source = {}) {
        if (!("feedId" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["feedId"] = 0;
        }
        if (!("newItems" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["newItems"] = 0;
        }
        if (!("notModified" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["notModified"] = false;
        }
        if (!("error" in $$source)) {
            /**
             * 该源抓取失败时的错误信息，空表示成功
             * @member
             * @type {string}
             */
            this["error"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RefreshOutcome instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {RefreshOutcome}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RefreshOutcome(/** @type {Partial<RefreshOutcome>} */($$parsedSource));
    }
}
