// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * OPMLBackupService 提供 OPML 订阅列表的云备份能力。
 * 
 * 备份为纯手动触发：没有后台定时器，也不在启动时安排任何任务。仍保留一个
 * 取消钩子，供退出时打断正在进行的手动备份/恢复，之后 main 才能安全关库。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as opmlbackup$0 from "../internal/opmlbackup/models.js";

/**
 * BackupOPMLToCloud 执行一次 OPML 备份。
 * @returns {$CancellablePromise<opmlbackup$0.BackupInfo>}
 */
export function BackupOPMLToCloud() {
    return $Call.ByID(1806090794).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * DeleteOPMLBackup 删除指定的远端 OPML 备份。
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function DeleteOPMLBackup(id) {
    return $Call.ByID(2548658063, id);
}

/**
 * GetOPMLBackupConfig 读取 OPML 备份配置。
 * @returns {$CancellablePromise<opmlbackup$0.Config>}
 */
export function GetOPMLBackupConfig() {
    return $Call.ByID(2274420442).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * GetOPMLBackupStatus 读取 OPML 备份状态。
 * @returns {$CancellablePromise<opmlbackup$0.Status>}
 */
export function GetOPMLBackupStatus() {
    return $Call.ByID(398065430).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * ListOPMLBackups 列出远端所有 OPML 备份。
 * @returns {$CancellablePromise<opmlbackup$0.BackupInfo[]>}
 */
export function ListOPMLBackups() {
    return $Call.ByID(2944309569).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * OPMLBackupRemotePath 返回 OPML 备份远端目录。
 * @returns {$CancellablePromise<string>}
 */
export function OPMLBackupRemotePath() {
    return $Call.ByID(1885279133);
}

/**
 * RestoreOPMLFromCloud 从云备份恢复订阅列表。
 * @param {string} id
 * @returns {$CancellablePromise<opmlbackup$0.ImportResult>}
 */
export function RestoreOPMLFromCloud(id) {
    return $Call.ByID(4269187325, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * SaveOPMLBackupConfig 保存 OPML 备份配置（目前只有保留版本数）。
 * @param {opmlbackup$0.Config} cfg
 * @returns {$CancellablePromise<void>}
 */
export function SaveOPMLBackupConfig(cfg) {
    return $Call.ByID(3786200627, cfg);
}

// Private type creation functions
const $$createType0 = opmlbackup$0.BackupInfo.createFrom;
const $$createType1 = opmlbackup$0.OPMLBackupConfig.createFrom;
const $$createType2 = opmlbackup$0.OPMLBackupStatus.createFrom;
const $$createType3 = $Create.Array($$createType0);
const $$createType4 = opmlbackup$0.OPMLImportResult.createFrom;
