// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * OPMLService OPML 导入导出相关的绑定方法。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ExportOPML 将当前全部分类与订阅源导出为 OPML：弹出系统保存对话框选择位置后写盘。
 * 用户取消返回 (false, nil)；成功返回 (true, nil)。
 * @returns {$CancellablePromise<boolean>}
 */
export function ExportOPML() {
    return $Call.ByID(2703977254);
}

/**
 * ImportOPML 解析 OPML 文本并导入分类与订阅源。
 * 导入仅根据 OPML 元信息建源，不发起网络抓取；文章将在下次调度或手动刷新时拉取。
 * @param {string} content
 * @returns {$CancellablePromise<$models.ImportResult>}
 */
export function ImportOPML(content) {
    return $Call.ByID(1457081217, content).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

// Private type creation functions
const $$createType0 = $models.ImportResult.createFrom;
