// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SettingsService 应用设置相关的绑定方法。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as store$0 from "../internal/store/models.js";

/**
 * BackupDatabase 弹出保存对话框，让用户选择位置后备份数据库。
 * 用户取消时返回 (false, nil)；成功返回 (true, nil)。
 * @returns {$CancellablePromise<boolean>}
 */
export function BackupDatabase() {
    return $Call.ByID(2885027906);
}

/**
 * ClearCache 清理缓存：删除已读且未收藏的文章并回收空间，返回删除条数。
 * @returns {$CancellablePromise<number>}
 */
export function ClearCache() {
    return $Call.ByID(3827582920);
}

/**
 * DatabasePath 返回数据库文件路径，供设置面板「数据管理」展示。
 * @returns {$CancellablePromise<string>}
 */
export function DatabasePath() {
    return $Call.ByID(1471848455);
}

/**
 * GetSettings 读取全局设置（未持久化时返回默认值）。
 * @returns {$CancellablePromise<store$0.Settings>}
 */
export function GetSettings() {
    return $Call.ByID(1931376994).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * RestoreDatabase 弹出打开对话框选择备份文件，校验后暂存为待恢复库，
 * 实际换库在下次启动生效（前端据此提示用户重启）。
 * 用户取消时返回 (false, nil)；暂存成功返回 (true, nil)。
 * @returns {$CancellablePromise<boolean>}
 */
export function RestoreDatabase() {
    return $Call.ByID(3634669908);
}

/**
 * TestProxy 测试代理连通性：用指定代理请求一个测试 URL，成功返回 nil。
 * @param {string} host
 * @param {number} port
 * @returns {$CancellablePromise<void>}
 */
export function TestProxy(host, port) {
    return $Call.ByID(3780555523, host, port);
}

/**
 * UpdateSettings 保存全局设置并同步调度器与代理配置。
 * @param {store$0.Settings} settings
 * @returns {$CancellablePromise<void>}
 */
export function UpdateSettings(settings) {
    return $Call.ByID(3408111713, settings);
}

// Private type creation functions
const $$createType0 = store$0.Settings.createFrom;
