// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SettingsService 应用设置相关的绑定方法。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as store$0 from "../internal/store/models.js";

/**
 * GetSettings 读取全局设置（未持久化时返回默认值）。
 * @returns {$CancellablePromise<store$0.Settings>}
 */
export function GetSettings() {
    return $Call.ByID(1931376994).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * UpdateSettings 保存全局设置。
 * @param {store$0.Settings} settings
 * @returns {$CancellablePromise<void>}
 */
export function UpdateSettings(settings) {
    return $Call.ByID(3408111713, settings);
}

// Private type creation functions
const $$createType0 = store$0.Settings.createFrom;
