// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SyncService 配置同步的绑定方法。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as syncer$0 from "../internal/syncer/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ClearWebDAVConfig 删除全部同步配置（含密码）。
 * @returns {$CancellablePromise<void>}
 */
export function ClearWebDAVConfig() {
    return $Call.ByID(647940195);
}

/**
 * GetSyncStatus 上次同步时间 / 上次错误 / 是否有待推送改动。
 * @returns {$CancellablePromise<syncer$0.Status>}
 */
export function GetSyncStatus() {
    return $Call.ByID(1585359264).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * GetWebDAVConfig 读取同步配置。不含密码，只带 hasPassword。
 * @returns {$CancellablePromise<syncer$0.WebDAVView>}
 */
export function GetWebDAVConfig() {
    return $Call.ByID(1127754958).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * RemoteFilePath 返回同步文件相对用户所填地址的路径（如 clip/settings.json）。
 * 
 * 给设置页拼完整路径用。之所以从后端要而不在前端写死：clip/ 这一层是我们自己
 * 建的，用户填 …/dav/ 最终会落到 …/dav/clip/settings.json，界面必须把这个
 * 完整位置讲清楚。路径的唯一定义处在 syncer，抄一份到前端就会有漂移的可能。
 * @returns {$CancellablePromise<string>}
 */
export function RemoteFilePath() {
    return $Call.ByID(294433860);
}

/**
 * ResolveConflict 按用户的选择解决冲突：keepLocal 为真用本地覆盖远端。
 * @param {boolean} keepLocal
 * @returns {$CancellablePromise<syncer$0.Result>}
 */
export function ResolveConflict(keepLocal) {
    return $Call.ByID(511335987, keepLocal).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * SaveWebDAVConfig 保存同步配置。密码传空串表示保持原密码不变。
 * @param {syncer$0.WebDAVInput} cfg
 * @returns {$CancellablePromise<void>}
 */
export function SaveWebDAVConfig(cfg) {
    return $Call.ByID(1366859581, cfg);
}

/**
 * SyncNow 立即同步一次。
 * @returns {$CancellablePromise<syncer$0.Result>}
 */
export function SyncNow() {
    return $Call.ByID(186052648).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * TestWebDAVConnection 建目录 + 写探针文件 + 删除，逐项报错。
 * 
 * 传入的是**尚未保存**的表单配置：用户改完就点测试，不该先被迫保存一份
 * 可能连不上的配置。密码留空时回落到已存的密码。
 * @param {syncer$0.WebDAVInput} cfg
 * @returns {$CancellablePromise<$models.ConnectionTestResult>}
 */
export function TestWebDAVConnection(cfg) {
    return $Call.ByID(2751204594, cfg).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

// Private type creation functions
const $$createType0 = syncer$0.Status.createFrom;
const $$createType1 = syncer$0.WebDAVView.createFrom;
const $$createType2 = syncer$0.Result.createFrom;
const $$createType3 = $models.ConnectionTestResult.createFrom;
