// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SystemService 提供与运行平台相关的信息，暴露给前端用于平台差异化渲染。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * CheckForUpdates 供前端调用（如设置-关于页的「检查更新」按钮），触发与菜单
 * 「Check for Updates…」相同的更新流程：弹出 Software Update 窗口 + 只做检查。
 * @returns {$CancellablePromise<void>}
 */
export function CheckForUpdates() {
    return $Call.ByID(3236035852);
}

/**
 * CheckForUpdatesSilent 供前端在启动时调用，触发静默更新检查（后台运行，不弹窗）。
 * 若有新版本可用，会通过 "clip:update:available" 事件通知前端。
 * @returns {$CancellablePromise<void>}
 */
export function CheckForUpdatesSilent() {
    return $Call.ByID(3958633237);
}

/**
 * IsOnline 探测网络连通性，返回 true 表示在线，false 表示离线。
 * 
 * 实现方式：尝试连接 Google Public DNS (8.8.8.8:53)，超时 2 秒。
 * 该方法简单快速，但无法区分"本地网络正常但外网不通"的情况。
 * @returns {$CancellablePromise<boolean>}
 */
export function IsOnline() {
    return $Call.ByID(4195382262);
}

/**
 * Platform 返回当前运行的操作系统标识。
 * 
 * 仅区分本项目支持的两个桌面平台：
 *   - "mac"     — macOS（runtime.GOOS == "darwin"）
 *   - "windows" — Windows 及其它
 * @returns {$CancellablePromise<string>}
 */
export function Platform() {
    return $Call.ByID(2821667470);
}

/**
 * SetTheme 在非 Windows 平台上是空操作。
 * 
 * macOS 使用隐藏式标题栏（MacTitleBarHiddenInset），无需切换原生主题。
 * @param {string} mode
 * @returns {$CancellablePromise<void>}
 */
export function SetTheme(mode) {
    return $Call.ByID(1434316160, mode);
}

/**
 * Version 返回当前应用版本号，供设置-关于页展示。
 * @returns {$CancellablePromise<string>}
 */
export function Version() {
    return $Call.ByID(4285456131);
}
