// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SystemService 提供与运行平台相关的信息，暴露给前端用于平台差异化渲染。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * Platform 返回当前运行的操作系统标识。
 * 
 * 仅区分本项目支持的两个桌面平台：
 *   - "mac"     — macOS（runtime.GOOS == "darwin"）
 *   - "windows" — Windows 及其它
 * @returns {$CancellablePromise<string>}
 */
export function Platform() {
    return $Call.ByID(2821667470);
}

/**
 * SetTheme 在非 Windows 平台上是空操作。
 * 
 * macOS 使用隐藏式标题栏（MacTitleBarHiddenInset），无需切换原生主题。
 * @param {string} mode
 * @returns {$CancellablePromise<void>}
 */
export function SetTheme(mode) {
    return $Call.ByID(1434316160, mode);
}
