// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * WebDAVConfigService WebDAV 凭据与连接管理服务。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as webdav$0 from "../internal/webdav/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ClearWebDAVConfig 删除全部 WebDAV 配置（含密码）。
 * @returns {$CancellablePromise<void>}
 */
export function ClearWebDAVConfig() {
    return $Call.ByID(1105691039);
}

/**
 * GetWebDAVClient 返回当前配置的 WebDAV 客户端，供其他服务使用。
 * @returns {$CancellablePromise<webdav$0.Client | null>}
 */
export function GetWebDAVClient() {
    return $Call.ByID(3746423651).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * GetWebDAVConfig 读取 WebDAV 配置。不含密码，只带 hasPassword。
 * @returns {$CancellablePromise<$models.WebDAVView>}
 */
export function GetWebDAVConfig() {
    return $Call.ByID(3582586738).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * SaveWebDAVConfig 保存 WebDAV 配置。密码传空串表示保持原密码不变。
 * @param {$models.WebDAVInput} cfg
 * @returns {$CancellablePromise<void>}
 */
export function SaveWebDAVConfig(cfg) {
    return $Call.ByID(717541857, cfg);
}

/**
 * TestWebDAVConnection 建目录 + 写探针文件 + 删除，逐项报错。
 * 
 * 传入的是**尚未保存**的表单配置：用户改完就点测试，不该先被迫保存。
 * 密码留空时回落到已存的密码。
 * @param {$models.WebDAVInput} cfg
 * @returns {$CancellablePromise<$models.ConnectionTestResult>}
 */
export function TestWebDAVConnection(cfg) {
    return $Call.ByID(3897038246, cfg).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

// Private type creation functions
const $$createType0 = webdav$0.Client.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $models.WebDAVView.createFrom;
const $$createType3 = $models.ConnectionTestResult.createFrom;
