// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../../../time/models.js";

/**
 * BackupInfo 单份备份的信息。
 */
export class BackupInfo {
    /**
     * Creates a new BackupInfo instance.
     * @param {Partial<BackupInfo>} [$$source = {}] - The source object to create the BackupInfo.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * 备份 ID（文件名）
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("deviceName" in $$source)) {
            /**
             * 创建备份的设备名
             * @member
             * @type {string}
             */
            this["deviceName"] = "";
        }
        if (!("createdAt" in $$source)) {
            /**
             * 创建时间
             * @member
             * @type {time$0.Time}
             */
            this["createdAt"] = null;
        }
        if (!("size" in $$source)) {
            /**
             * 文件大小（字节）
             * @member
             * @type {number}
             */
            this["size"] = 0;
        }
        if (!("lastModified" in $$source)) {
            /**
             * 最后修改时间
             * @member
             * @type {time$0.Time}
             */
            this["lastModified"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BackupInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {BackupInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new BackupInfo(/** @type {Partial<BackupInfo>} */($$parsedSource));
    }
}

/**
 * OPMLBackupConfig OPML 云备份配置。
 * 
 * 只保留清理策略：备份改为纯手动触发，不再有自动周期。Retention 控制每次
 * 备份（含手动）后保留的历史版本数，避免快照无限堆积。
 */
export class OPMLBackupConfig {
    /**
     * Creates a new OPMLBackupConfig instance.
     * @param {Partial<OPMLBackupConfig>} [$$source = {}] - The source object to create the OPMLBackupConfig.
     */
    constructor($$source = {}) {
        if (!("retention" in $$source)) {
            /**
             * 保留版本数
             * @member
             * @type {number}
             */
            this["retention"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new OPMLBackupConfig instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {OPMLBackupConfig}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new OPMLBackupConfig(/** @type {Partial<OPMLBackupConfig>} */($$parsedSource));
    }
}

/**
 * Config OPML 云备份配置（对外导出）。
 */
export const Config = OPMLBackupConfig;

/**
 * Config OPML 云备份配置（对外导出）。
 * @typedef {OPMLBackupConfig} Config
 */

/**
 * OPMLBackupStatus OPML 云备份状态。
 */
export class OPMLBackupStatus {
    /**
     * Creates a new OPMLBackupStatus instance.
     * @param {Partial<OPMLBackupStatus>} [$$source = {}] - The source object to create the OPMLBackupStatus.
     */
    constructor($$source = {}) {
        if (!("lastBackupAt" in $$source)) {
            /**
             * 上次备份时间
             * @member
             * @type {time$0.Time}
             */
            this["lastBackupAt"] = null;
        }
        if (!("lastError" in $$source)) {
            /**
             * 上次错误信息
             * @member
             * @type {string}
             */
            this["lastError"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new OPMLBackupStatus instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {OPMLBackupStatus}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new OPMLBackupStatus(/** @type {Partial<OPMLBackupStatus>} */($$parsedSource));
    }
}

/**
 * OPMLImportResult OPML 导入结果。
 */
export class OPMLImportResult {
    /**
     * Creates a new OPMLImportResult instance.
     * @param {Partial<OPMLImportResult>} [$$source = {}] - The source object to create the OPMLImportResult.
     */
    constructor($$source = {}) {
        if (!("Categories" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["Categories"] = 0;
        }
        if (!("Feeds" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["Feeds"] = 0;
        }
        if (!("Skipped" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["Skipped"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new OPMLImportResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {OPMLImportResult}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new OPMLImportResult(/** @type {Partial<OPMLImportResult>} */($$parsedSource));
    }
}

/**
 * ImportResult OPML 导入结果（对外导出）。
 */
export const ImportResult = OPMLImportResult;

/**
 * ImportResult OPML 导入结果（对外导出）。
 * @typedef {OPMLImportResult} ImportResult
 */

/**
 * Status OPML 云备份状态（对外导出）。
 */
export const Status = OPMLBackupStatus;

/**
 * Status OPML 云备份状态（对外导出）。
 * @typedef {OPMLBackupStatus} Status
 */
