// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../../../time/models.js";

/**
 * BackupInfo 描述一个不可变数据库快照。
 */
export class BackupInfo {
    /**
     * Creates a new BackupInfo instance.
     * @param {Partial<BackupInfo>} [$$source = {}] - The source object to create the BackupInfo.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("file" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["file"] = "";
        }
        if (!("deviceName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["deviceName"] = "";
        }
        if (!("createdAt" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["createdAt"] = null;
        }
        if (!("size" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["size"] = 0;
        }
        if (!("sha256" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["sha256"] = "";
        }
        if (!("databaseVersion" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["databaseVersion"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BackupInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {BackupInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new BackupInfo(/** @type {Partial<BackupInfo>} */($$parsedSource));
    }
}

/**
 * Config 自动云备份配置。手动备份不受 Enabled 限制。
 */
export class Config {
    /**
     * Creates a new Config instance.
     * @param {Partial<Config>} [$$source = {}] - The source object to create the Config.
     */
    constructor($$source = {}) {
        if (!("enabled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["enabled"] = false;
        }
        if (!("interval" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["interval"] = "";
        }
        if (!("retention" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["retention"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Config instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Config}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Config(/** @type {Partial<Config>} */($$parsedSource));
    }
}

/**
 * RestoreResult 表示快照已安全暂存，需重启应用完成换库。
 */
export class RestoreResult {
    /**
     * Creates a new RestoreResult instance.
     * @param {Partial<RestoreResult>} [$$source = {}] - The source object to create the RestoreResult.
     */
    constructor($$source = {}) {
        if (!("restartRequired" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["restartRequired"] = false;
        }
        if (!("rollbackPath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["rollbackPath"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RestoreResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {RestoreResult}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RestoreResult(/** @type {Partial<RestoreResult>} */($$parsedSource));
    }
}

/**
 * Status 本机最近一次云备份/恢复状态。远端历史由 List 单独读取。
 */
export class Status {
    /**
     * Creates a new Status instance.
     * @param {Partial<Status>} [$$source = {}] - The source object to create the Status.
     */
    constructor($$source = {}) {
        if (!("lastBackupAt" in $$source)) {
            /**
             * @member
             * @type {time$0.Time | null}
             */
            this["lastBackupAt"] = null;
        }
        if (!("lastAttemptAt" in $$source)) {
            /**
             * @member
             * @type {time$0.Time | null}
             */
            this["lastAttemptAt"] = null;
        }
        if (!("lastBackup" in $$source)) {
            /**
             * @member
             * @type {BackupInfo | null}
             */
            this["lastBackup"] = null;
        }
        if (!("lastRestoreAt" in $$source)) {
            /**
             * @member
             * @type {time$0.Time | null}
             */
            this["lastRestoreAt"] = null;
        }
        if (!("lastError" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["lastError"] = "";
        }
        if (!("nextBackupAt" in $$source)) {
            /**
             * @member
             * @type {time$0.Time | null}
             */
            this["nextBackupAt"] = null;
        }
        if (!("rollbackPath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["rollbackPath"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Status instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Status}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("lastBackup" in $$parsedSource) {
            $$parsedSource["lastBackup"] = $$createField2_0($$parsedSource["lastBackup"]);
        }
        return new Status(/** @type {Partial<Status>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = BackupInfo.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
