// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../../../time/models.js";

/**
 * Category 订阅源分类（支持树形结构）
 */
export class Category {
    /**
     * Creates a new Category instance.
     * @param {Partial<Category>} [$$source = {}] - The source object to create the Category.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["id"] = 0;
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("parentId" in $$source)) {
            /**
             * null 表示根分类
             * @member
             * @type {number | null}
             */
            this["parentId"] = null;
        }
        if (!("sortOrder" in $$source)) {
            /**
             * 排序权重
             * @member
             * @type {number}
             */
            this["sortOrder"] = 0;
        }
        if (!("createdAt" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["createdAt"] = null;
        }
        if (!("updatedAt" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["updatedAt"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Category instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Category}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Category(/** @type {Partial<Category>} */($$parsedSource));
    }
}

/**
 * CategoryWithFeeds 分类附带订阅源列表
 */
export class CategoryWithFeeds {
    /**
     * Creates a new CategoryWithFeeds instance.
     * @param {Partial<CategoryWithFeeds>} [$$source = {}] - The source object to create the CategoryWithFeeds.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["id"] = 0;
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("parentId" in $$source)) {
            /**
             * null 表示根分类
             * @member
             * @type {number | null}
             */
            this["parentId"] = null;
        }
        if (!("sortOrder" in $$source)) {
            /**
             * 排序权重
             * @member
             * @type {number}
             */
            this["sortOrder"] = 0;
        }
        if (!("createdAt" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["createdAt"] = null;
        }
        if (!("updatedAt" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["updatedAt"] = null;
        }
        if (!("feeds" in $$source)) {
            /**
             * @member
             * @type {FeedWithUnread[]}
             */
            this["feeds"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CategoryWithFeeds instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {CategoryWithFeeds}
     */
    static createFrom($$source = {}) {
        const $$createField6_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("feeds" in $$parsedSource) {
            $$parsedSource["feeds"] = $$createField6_0($$parsedSource["feeds"]);
        }
        return new CategoryWithFeeds(/** @type {Partial<CategoryWithFeeds>} */($$parsedSource));
    }
}

/**
 * Feed RSS/Atom 订阅源
 */
export class Feed {
    /**
     * Creates a new Feed instance.
     * @param {Partial<Feed>} [$$source = {}] - The source object to create the Feed.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["id"] = 0;
        }
        if (!("url" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["url"] = "";
        }
        if (!("title" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["title"] = "";
        }
        if (!("description" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["description"] = "";
        }
        if (!("link" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["link"] = "";
        }
        if (!("icon" in $$source)) {
            /**
             * favicon URL
             * @member
             * @type {string}
             */
            this["icon"] = "";
        }
        if (!("categoryId" in $$source)) {
            /**
             * 可选分类
             * @member
             * @type {number | null}
             */
            this["categoryId"] = null;
        }
        if (!("updateInterval" in $$source)) {
            /**
             * 更新间隔（分钟）
             * @member
             * @type {number}
             */
            this["updateInterval"] = 0;
        }
        if (!("maxItems" in $$source)) {
            /**
             * 最大保留条目数
             * @member
             * @type {number}
             */
            this["maxItems"] = 0;
        }
        if (!("lastUpdated" in $$source)) {
            /**
             * 可为 NULL
             * @member
             * @type {time$0.Time | null}
             */
            this["lastUpdated"] = null;
        }
        if (!("errorCount" in $$source)) {
            /**
             * 连续错误次数
             * @member
             * @type {number}
             */
            this["errorCount"] = 0;
        }
        if (!("lastError" in $$source)) {
            /**
             * 可为 NULL
             * @member
             * @type {string | null}
             */
            this["lastError"] = null;
        }
        if (!("status" in $$source)) {
            /**
             * active/paused/error
             * @member
             * @type {string}
             */
            this["status"] = "";
        }
        if (!("createdAt" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["createdAt"] = null;
        }
        if (!("updatedAt" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["updatedAt"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Feed instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Feed}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Feed(/** @type {Partial<Feed>} */($$parsedSource));
    }
}

/**
 * FeedWithUnread Feed 附带未读计数
 */
export class FeedWithUnread {
    /**
     * Creates a new FeedWithUnread instance.
     * @param {Partial<FeedWithUnread>} [$$source = {}] - The source object to create the FeedWithUnread.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["id"] = 0;
        }
        if (!("url" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["url"] = "";
        }
        if (!("title" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["title"] = "";
        }
        if (!("description" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["description"] = "";
        }
        if (!("link" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["link"] = "";
        }
        if (!("icon" in $$source)) {
            /**
             * favicon URL
             * @member
             * @type {string}
             */
            this["icon"] = "";
        }
        if (!("categoryId" in $$source)) {
            /**
             * 可选分类
             * @member
             * @type {number | null}
             */
            this["categoryId"] = null;
        }
        if (!("updateInterval" in $$source)) {
            /**
             * 更新间隔（分钟）
             * @member
             * @type {number}
             */
            this["updateInterval"] = 0;
        }
        if (!("maxItems" in $$source)) {
            /**
             * 最大保留条目数
             * @member
             * @type {number}
             */
            this["maxItems"] = 0;
        }
        if (!("lastUpdated" in $$source)) {
            /**
             * 可为 NULL
             * @member
             * @type {time$0.Time | null}
             */
            this["lastUpdated"] = null;
        }
        if (!("errorCount" in $$source)) {
            /**
             * 连续错误次数
             * @member
             * @type {number}
             */
            this["errorCount"] = 0;
        }
        if (!("lastError" in $$source)) {
            /**
             * 可为 NULL
             * @member
             * @type {string | null}
             */
            this["lastError"] = null;
        }
        if (!("status" in $$source)) {
            /**
             * active/paused/error
             * @member
             * @type {string}
             */
            this["status"] = "";
        }
        if (!("createdAt" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["createdAt"] = null;
        }
        if (!("updatedAt" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["updatedAt"] = null;
        }
        if (!("unreadCount" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["unreadCount"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FeedWithUnread instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {FeedWithUnread}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FeedWithUnread(/** @type {Partial<FeedWithUnread>} */($$parsedSource));
    }
}

/**
 * Item RSS 文章条目
 */
export class Item {
    /**
     * Creates a new Item instance.
     * @param {Partial<Item>} [$$source = {}] - The source object to create the Item.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["id"] = 0;
        }
        if (!("feedId" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["feedId"] = 0;
        }
        if (!("title" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["title"] = "";
        }
        if (!("author" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["author"] = "";
        }
        if (!("publishedAt" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["publishedAt"] = null;
        }
        if (!("updatedAt" in $$source)) {
            /**
             * 可为 NULL
             * @member
             * @type {time$0.Time | null}
             */
            this["updatedAt"] = null;
        }
        if (!("url" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["url"] = "";
        }
        if (!("content" in $$source)) {
            /**
             * 完整内容
             * @member
             * @type {string}
             */
            this["content"] = "";
        }
        if (!("summary" in $$source)) {
            /**
             * 摘要
             * @member
             * @type {string}
             */
            this["summary"] = "";
        }
        if (!("enclosure" in $$source)) {
            /**
             * 附件 URL（音频/视频）
             * @member
             * @type {string}
             */
            this["enclosure"] = "";
        }
        if (!("categories" in $$source)) {
            /**
             * JSON 数组字符串
             * @member
             * @type {string}
             */
            this["categories"] = "";
        }
        if (!("isRead" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["isRead"] = false;
        }
        if (!("isStarred" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["isStarred"] = false;
        }
        if (!("readAt" in $$source)) {
            /**
             * 可为 NULL
             * @member
             * @type {time$0.Time | null}
             */
            this["readAt"] = null;
        }
        if (!("note" in $$source)) {
            /**
             * 用户笔记
             * @member
             * @type {string}
             */
            this["note"] = "";
        }
        if (!("createdAt" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["createdAt"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Item instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Item}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Item(/** @type {Partial<Item>} */($$parsedSource));
    }
}

/**
 * Settings 应用全局设置。
 */
export class Settings {
    /**
     * Creates a new Settings instance.
     * @param {Partial<Settings>} [$$source = {}] - The source object to create the Settings.
     */
    constructor($$source = {}) {
        if (!("theme" in $$source)) {
            /**
             * system / light / dark
             * @member
             * @type {string}
             */
            this["theme"] = "";
        }
        if (!("language" in $$source)) {
            /**
             * zh / en
             * @member
             * @type {string}
             */
            this["language"] = "";
        }
        if (!("defaultUpdateInterval" in $$source)) {
            /**
             * 默认更新间隔（分钟）
             * @member
             * @type {number}
             */
            this["defaultUpdateInterval"] = 0;
        }
        if (!("defaultMaxItems" in $$source)) {
            /**
             * 默认每源最大保留条目数
             * @member
             * @type {number}
             */
            this["defaultMaxItems"] = 0;
        }
        if (!("notificationMode" in $$source)) {
            /**
             * each / summary / off
             * @member
             * @type {string}
             */
            this["notificationMode"] = "";
        }
        if (!("showUnreadBadge" in $$source)) {
            /**
             * 是否在 Dock 图标展示未读角标（仅 macOS）
             * @member
             * @type {boolean}
             */
            this["showUnreadBadge"] = false;
        }
        if (!("autoMarkReadDelay" in $$source)) {
            /**
             * 自动标记已读延迟（毫秒）：-1 关闭 / 0 立即 / >0 延迟
             * @member
             * @type {number}
             */
            this["autoMarkReadDelay"] = 0;
        }
        if (!("launchMinimized" in $$source)) {
            /**
             * 启动时最小化窗口
             * @member
             * @type {boolean}
             */
            this["launchMinimized"] = false;
        }
        if (!("windowWidth" in $$source)) {
            /**
             * 主窗口上次关闭时的宽度
             * @member
             * @type {number}
             */
            this["windowWidth"] = 0;
        }
        if (!("windowHeight" in $$source)) {
            /**
             * 主窗口上次关闭时的高度
             * @member
             * @type {number}
             */
            this["windowHeight"] = 0;
        }
        if (!("proxyHost" in $$source)) {
            /**
             * HTTP 代理 IP / 主机名
             * @member
             * @type {string}
             */
            this["proxyHost"] = "";
        }
        if (!("proxyPort" in $$source)) {
            /**
             * HTTP 代理端口
             * @member
             * @type {number}
             */
            this["proxyPort"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Settings instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Settings}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Settings(/** @type {Partial<Settings>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = FeedWithUnread.createFrom;
const $$createType1 = $Create.Array($$createType0);
